# <img style="float: left; padding-right: 20px; width: 200px" src="https://raw.githubusercontent.com/raxlab/imt2200-data/main/media/logo.jpg">  IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Profesor:** Rodrigo A. Carrasco <br>
---

# <h1><center>Clase 10: Transformación de Datos</center></h1>

En este notebook comenzaremos el trabajo de transformación, con el objetivo de que los estudiantes del curso aprendan diferentes comandos y técnicas en Python y, en particular, en Pandas, para la transformación de datos.

## 1. Transformación de datos.

El set de datos que utilizaremos en este ejercicio será la base proviente de la página `insideairbnb.com`. EL archivo particular usado está dispobible en la carpeta `data` junto a este Notebook.

In [2]:
# lectura de datos
import pandas as pd
import os

ruta = os.path.join('data', 'listings.csv')
df = pd.read_csv(ruta)
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,7.709720e+17,https://www.airbnb.com/rooms/770971877915057044,2.023060e+13,6/28/2023,previous scrape,Home in Las Condes · 1 bedroom · 1 bed · 1 pri...,Dormitorio en el primer piso con baño privado ...,NaN,https://a0.muscache.com/pictures/c23b8b00-aae8...,365532508,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
1,7.602830e+17,https://www.airbnb.com/rooms/760282894651545802,2.023060e+13,6/28/2023,previous scrape,Rental unit in Santiago · ★4.63 · 1 bedroom · ...,Disfruta del fácil acceso a todo desde este al...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,95873591,...,4.81,4.81,4.81,NaN,f,3,3,0,0,2.23
2,5.186899e+07,https://www.airbnb.com/rooms/51868986,2.023060e+13,6/28/2023,city scrape,Rental unit in Providencia · ★4.55 · 1 bedroom...,NaN,NaN,https://a0.muscache.com/pictures/855ada98-d368...,249113475,...,4.48,4.93,4.48,NaN,f,21,21,0,0,1.39
3,1.779192e+07,https://www.airbnb.com/rooms/17791924,2.023060e+13,6/28/2023,city scrape,Rental unit in Vitacura · ★4.95 · 1 bedroom · ...,** Alquiler MENSUAL disponible con dcto<br /><...,"Located in VITACURA, the upper side of the cit...",https://a0.muscache.com/pictures/4e5a0a16-b0c7...,3282957,...,5.00,4.97,4.92,NaN,f,2,2,0,0,0.50
4,3.881542e+07,https://www.airbnb.com/rooms/38815415,2.023060e+13,6/28/2023,city scrape,Rental unit in Santiago · 1 bedroom · 1 bed · ...,"Buena Ubicación, metro Cumming, departamento c...",NaN,https://a0.muscache.com/pictures/ffaaf578-3455...,296973826,...,5.00,5.00,5.00,NaN,f,1,0,1,0,0.04

### 1.1 Tipos de Datos

Veamos los diferentes comandos que nos permiten entender qué tipos de datos tenemos en cada columna de nuestro DataFrame y lograr algún nivel general de descripción.

In [3]:
df.dtypes

id                                              float64
listing_url                                      object
scrape_id                                       float64
last_scraped                                     object
source                                           object
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 75, dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10557 entries, 0 to 10556
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            10557 non-null  float64
 1   listing_url                                   10557 non-null  object
 2   scrape_id                                     10557 non-null  float64
 3   last_scraped                                  10557 non-null  object
 4   source                                        10557 non-null  object
 5   name                                          10557 non-null  object
 6   description                                   10214 non-null  object
 7   neighborhood_overview                         5065 non-null   object
 8   picture_url                                   10556 non-null  object
 9   host_id                                       10557 non-null  int64
 10  host_url                                      10557 non-null  object
 11  host_name                                     10557 non-null  object
 12  host_since                                    10557 non-null  object
 13  host_location                                 7063 non-null   object
 14  host_about                                    4785 non-null   object
 15  host_response_time                            7879 non-null   object
 16  host_response_rate                            7879 non-null   object
 17  host_acceptance_rate                          8587 non-null   object
 18  host_is_superhost                             7539 non-null   object
 19  host_thumbnail_url                            10557 non-null  object
 20  host_picture_url                              10557 non-null  object
 21  host_neighbourhood                            1532 non-null   object
 22  host_listings_count                           10557 non-null  int64
 23  host_total_listings_count                     10557 non-null  int64
 24  host_verifications                            10557 non-null  object
 25  host_has_profile_pic                          10557 non-null  object
 26  host_identity_verified                        10557 non-null  object
 27  neighbourhood                                 5065 non-null   object
 28  neighbourhood_cleansed                        10557 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      10557 non-null  float64
 31  longitude                                     10557 non-null  float64
 32  property_type                                 10557 non-null  object
 33  room_type                                     10557 non-null  object
 34  accommodates                                  10557 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                10527 non-null  object
 37  bedrooms                                      7501 non-null   float64
 38  beds                                          10434 non-null  float64
 39  amenities                                     10557 non-null  object
 40  price                                         10557 non-null  object
 41  minimum_nights                                10557 non-null  int64
 42  maximum_nights                                10557 non-null  int64
 43  minimum_minimum_nights                        10557 non-null  int64
 44  maximum_minimum_nights                        10557 non-null  int64
 45  minimum_maximum_nights                        10557 non-null  int64
 46  maximum_maximum_nights                        10557 non-null  int64
 47  minimum_nights_avg_ntm                        10557 non-null  float64
 48  maximum_nights_avg_ntm                        10557 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              10557 non-null  object
 51  availability_30                               10557 non-null  int64
 52  availability_60                               10557 non-null  int64
 53  availability_90                               10557 non-null  int64
 54  availability_365                              10557 non-null  int64
 55  calendar_last_scraped                         10557 non-null  object
 56  number_of_reviews                             10557 non-null  int64
 57  number_of_reviews_ltm                         10557 non-null  int64
 58  number_of_reviews_l30d                        10557 non-null  int64
 59  first_review                                  7874 non-null   object
 60  last_review                                   7874 non-null   object
 61  review_scores_rating                          7874 non-null   float64
 62  review_scores_accuracy                        7815 non-null   float64
 63  review_scores_cleanliness                     7814 non-null   float64
 64  review_scores_checkin                         7814 non-null   float64
 65  review_scores_communication                   7815 non-null   float64
 66  review_scores_location                        7813 non-null   float64
 67  review_scores_value                           7814 non-null   float64
 68  license                                       198 non-null    object
 69  instant_bookable                              10557 non-null  object
 70  calculated_host_listings_count                10557 non-null  int64
 71  calculated_host_listings_count_entire_homes   10557 non-null  int64
 72  calculated_host_listings_count_private_rooms  10557 non-null  int64
 73  calculated_host_listings_count_shared_rooms   10557 non-null  int64
 74  reviews_per_month                             7874 non-null   float64
dtypes: float64(19), int64(21), object(35)
memory usage: 6.0+ MB

In [ ]:
df['minimum_nights'].describe() #minima cantidad de noches

count    10557.000000
mean         6.955385
std         35.157352
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max       1124.000000
Name: minimum_nights, dtype: float64

Veamos ahora qué tenemos en la cantidad de baños de los lugares en arriendo.

In [8]:
df['bathrooms'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: bathrooms, dtype: float64

#Esta vacia la columna baños

Era una columna vacía que podemos eliminar dado que no tiene datos relevantes. Al revisar la base, nos damos cuenta que hay otra columna con los datos de la cantidad de baños.

In [9]:
df['bathrooms_text'].describe()

count      10527
unique        40
top       1 bath
freq        5080
Name: bathrooms_text, dtype: object

In [10]:
df['bathrooms_text']

0        1 private bath
1                1 bath
2                1 bath
3             1.5 baths
4         1 shared bath
              ...
10552            1 bath
10553           2 baths
10554            1 bath
10555            1 bath
10556           2 baths
Name: bathrooms_text, Length: 10557, dtype: object

Lamentablemente los baños contienen texto, por lo que no podemos usar `describe` para obtener la misma información que para columnas numéricas.

In [11]:
df['bedrooms'].describe()

count    7501.000000
mean        1.600853
std         1.106885
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        24.000000
Name: bedrooms, dtype: float64

In [12]:
df['bedrooms'] = df['bedrooms'].astype('category') #transformamos la columna beedrooms a categoria

In [13]:
df['bedrooms'].dtype

CategoricalDtype(categories=[ 1.0,  2.0,  3.0,  4.0,  5.0,  6.0,  7.0,  8.0,  9.0, 10.0,
                  11.0, 12.0, 14.0, 15.0, 16.0, 17.0, 23.0, 24.0],
, ordered=False, categories_dtype=float64)

Aprovechemos esta idea y transformemos los datos de baños en categorías, para ver si con eso podemos ordenar mejor esa información.

In [14]:
df['bathrooms_text'] = df['bathrooms_text'].astype('category')

In [15]:
df['bathrooms_text'].dtype

CategoricalDtype(categories=['0 baths', '0 shared baths', '1 bath', '1 private bath',
                  '1 shared bath', '1.5 baths', '1.5 shared baths', '10 baths',
                  '10.5 shared baths', '11.5 baths', '12 baths',
                  '16 shared baths', '2 baths', '2 shared baths', '2.5 baths',
                  '2.5 shared baths', '24 baths', '3 baths', '3 shared baths',
                  '3.5 baths', '3.5 shared baths', '4 baths', '4 shared baths',
                  '4.5 baths', '4.5 shared baths', '5 baths', '5 shared baths',
                  '5.5 baths', '5.5 shared baths', '6 baths', '6 shared baths',
                  '7 baths', '7 shared baths', '8 baths', '8.5 baths',
                  '8.5 shared baths', '9 baths', 'Half-bath',
                  'Private half-bath', 'Shared half-bath'],
, ordered=False, categories_dtype=object)

## 2 Datos Duplicados

Pandas tiene comandos especiales para identificar y trabajar con datos duplicados.

In [16]:
duplicates = df.duplicated(keep=False)
dups = df[duplicates].sort_values(by='id')
dups

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
429,1.859997e+07,https://www.airbnb.com/rooms/18599966,2.023060e+13,6/28/2023,city scrape,Home in Penalolen · 3 bedrooms · 1 bed · 1 pri...,"Casa acogedora, tranquila y confortable. Tendr...",NaN,https://a0.muscache.com/pictures/a4ac7163-78d6...,7151410,...,5.0,5.0,5.0,NaN,f,2,0,2,0,0.01
422,1.859997e+07,https://www.airbnb.com/rooms/18599966,2.023060e+13,6/28/2023,city scrape,Home in Penalolen · 3 bedrooms · 1 bed · 1 pri...,"Casa acogedora, tranquila y confortable. Tendr...",NaN,https://a0.muscache.com/pictures/a4ac7163-78d6...,7151410,...,5.0,5.0,5.0,NaN,f,2,0,2,0,0.01
235,8.681050e+17,https://www.airbnb.com/rooms/868105386849342885,2.023060e+13,6/28/2023,city scrape,Rental unit in Providencia · Studio · 1 bed · ...,Habitación ubicada en un sector de Providencia...,NaN,https://a0.muscache.com/pictures/89945e21-9f53...,225156218,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
224,8.681050e+17,https://www.airbnb.com/rooms/868105386849342885,2.023060e+13,6/28/2023,city scrape,Rental unit in Providencia · Studio · 1 bed · ...,Habitación ubicada en un sector de Providencia...,NaN,https://a0.muscache.com/pictures/89945e21-9f53...,225156218,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
13,8.899730e+17,https://www.airbnb.com/rooms/889972919307772272,2.023060e+13,6/28/2023,city scrape,Rental unit in Providencia · ★New · 1 bedroom ...,Este lugar único tiene su propio estilo.,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,75144753,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
21,8.899730e+17,https://www.airbnb.com/rooms/889972919307772272,2.023060e+13,6/28/2023,city scrape,Rental unit in Providencia · ★New · 1 bedroom ...,Este lugar único tiene su propio estilo.,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,75144753,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN

In [17]:
df = df.drop_duplicates(keep='first')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10554 entries, 0 to 10556
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            10554 non-null  float64
 1   listing_url                                   10554 non-null  object
 2   scrape_id                                     10554 non-null  float64
 3   last_scraped                                  10554 non-null  object
 4   source                                        10554 non-null  object
 5   name                                          10554 non-null  object
 6   description                                   10211 non-null  object
 7   neighborhood_overview                         5065 non-null   object
 8   picture_url                                   10553 non-null  object
 9   host_id                                       10554 non-null  int64
 10  host_url                                      10554 non-null  object
 11  host_name                                     10554 non-null  object
 12  host_since                                    10554 non-null  object
 13  host_location                                 7061 non-null   object
 14  host_about                                    4784 non-null   object
 15  host_response_time                            7876 non-null   object
 16  host_response_rate                            7876 non-null   object
 17  host_acceptance_rate                          8585 non-null   object
 18  host_is_superhost                             7538 non-null   object
 19  host_thumbnail_url                            10554 non-null  object
 20  host_picture_url                              10554 non-null  object
 21  host_neighbourhood                            1532 non-null   object
 22  host_listings_count                           10554 non-null  int64
 23  host_total_listings_count                     10554 non-null  int64
 24  host_verifications                            10554 non-null  object
 25  host_has_profile_pic                          10554 non-null  object
 26  host_identity_verified                        10554 non-null  object
 27  neighbourhood                                 5065 non-null   object
 28  neighbourhood_cleansed                        10554 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      10554 non-null  float64
 31  longitude                                     10554 non-null  float64
 32  property_type                                 10554 non-null  object
 33  room_type                                     10554 non-null  object
 34  accommodates                                  10554 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                10524 non-null  category
 37  bedrooms                                      7500 non-null   category
 38  beds                                          10431 non-null  float64
 39  amenities                                     10554 non-null  object
 40  price                                         10554 non-null  object
 41  minimum_nights                                10554 non-null  int64
 42  maximum_nights                                10554 non-null  int64
 43  minimum_minimum_nights                        10554 non-null  int64
 44  maximum_minimum_nights                        10554 non-null  int64
 45  minimum_maximum_nights                        10554 non-null  int64
 46  maximum_maximum_nights                        10554 non-null  int64
 47  minimum_nights_avg_ntm                        10554 non-null  float64
 48  maximum_nights_avg_ntm                        10554 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              10554 non-null  object
 51  availability_30                               10554 non-null  int64
 52  availability_60                               10554 non-null  int64
 53  availability_90                               10554 non-null  int64
 54  availability_365                              10554 non-null  int64
 55  calendar_last_scraped                         10554 non-null  object
 56  number_of_reviews                             10554 non-null  int64
 57  number_of_reviews_ltm                         10554 non-null  int64
 58  number_of_reviews_l30d                        10554 non-null  int64
 59  first_review                                  7873 non-null   object
 60  last_review                                   7873 non-null   object
 61  review_scores_rating                          7873 non-null   float64
 62  review_scores_accuracy                        7814 non-null   float64
 63  review_scores_cleanliness                     7813 non-null   float64
 64  review_scores_checkin                         7813 non-null   float64
 65  review_scores_communication                   7814 non-null   float64
 66  review_scores_location                        7812 non-null   float64
 67  review_scores_value                           7813 non-null   float64
 68  license                                       198 non-null    object
 69  instant_bookable                              10554 non-null  object
 70  calculated_host_listings_count                10554 non-null  int64
 71  calculated_host_listings_count_entire_homes   10554 non-null  int64
 72  calculated_host_listings_count_private_rooms  10554 non-null  int64
 73  calculated_host_listings_count_shared_rooms   10554 non-null  int64
 74  reviews_per_month                             7873 non-null   float64
dtypes: category(2), float64(18), int64(21), object(34)
memory usage: 6.0+ MB

## 3 Datos Nulos

Pandas tambien tiene funciones que nos permiten identificar valores nulos para luego corregir o limpiar.

In [19]:
nan_df = df['neighborhood_overview'].isna()

In [20]:
nan_df

0         True
1         True
2         True
3        False
4         True
         ...
10552     True
10553    False
10554     True
10555     True
10556    False
Name: neighborhood_overview, Length: 10554, dtype: bool

In [21]:
df.dropna(subset = ['neighborhood_overview'], inplace=True)

In [22]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
3,1.779192e+07,https://www.airbnb.com/rooms/17791924,2.023060e+13,6/28/2023,city scrape,Rental unit in Vitacura · ★4.95 · 1 bedroom · ...,** Alquiler MENSUAL disponible con dcto<br /><...,"Located in VITACURA, the upper side of the cit...",https://a0.muscache.com/pictures/4e5a0a16-b0c7...,3282957,...,5.00,4.97,4.92,NaN,f,2,2,0,0,0.50
7,6.738951e+06,https://www.airbnb.com/rooms/6738951,2.023060e+13,6/28/2023,city scrape,Loft in Recoleta · ★4.88 · 1 bedroom · 1 bed ·...,In this space we respect diversity and inclusi...,"Good neighborhood,bohemian,with bars around,li...",https://a0.muscache.com/pictures/2d370aad-e048...,35289741,...,4.98,4.92,4.92,NaN,t,1,1,0,0,2.68
10,1.787726e+07,https://www.airbnb.com/rooms/17877260,2.023060e+13,6/28/2023,city scrape,Rental unit in Vitacura · ★4.66 · 1 bedroom · ...,"Steps away from Parque Arauco Mall, and Kenned...",Las Condes has become one of the most sought a...,https://a0.muscache.com/pictures/eb3887b0-971c...,38381654,...,4.72,4.94,4.63,NaN,t,2,2,0,0,2.01
17,6.457040e+17,https://www.airbnb.com/rooms/645703653437227190,2.023060e+13,6/28/2023,city scrape,Serviced apartment in Santiago · ★4.50 · 2 bed...,Comfortable apartment located in the center of...,Located in the historic center of the city of ...,https://a0.muscache.com/pictures/miso/Hosting-...,189439813,...,4.75,4.75,4.63,NaN,t,40,21,19,0,0.67
18,6.050774e+06,https://www.airbnb.com/rooms/6050774,2.023060e+13,6/28/2023,city scrape,Rental unit in Santiago · 2 bedrooms · 2 beds ...,"Super comfortable 2 bedroom, 2 bath condo on t...",The apartment is in Santiago Central. Walk out...,https://a0.muscache.com/pictures/75369804/be1e...,7169912,...,5.00,5.00,5.00,NaN,f,1,1,0,0,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10546,1.125324e+07,https://www.airbnb.com/rooms/11253241,2.023060e+13,6/28/2023,city scrape,Rental unit in Santiago · ★4.78 · 3 bedrooms ·...,* A 3 calles de estación del METRO.<br />* Est...,El departamento se encuentra en un barrio trad...,https://a0.muscache.com/pictures/c127d3a5-ac18...,53778739,...,4.94,4.76,4.76,NaN,f,3,3,0,0,4.89
10547,3.718137e+07,https://www.airbnb.com/rooms/37181369,2.023060e+13,6/28/2023,city scrape,Rental unit in Recoleta · ★4.67 · 1 bedroom · ...,"Apartamento cómodo instalaciones, lavandería, ...",A minutos del Barrio Bellavista centro bohemio...,https://a0.muscache.com/pictures/9a09e16e-b8d4...,279796881,...,4.78,4.81,4.72,NaN,t,1,1,0,0,1.80
10549,7.291520e+17,https://www.airbnb.com/rooms/729151824622083237,2.023060e+13,6/28/2023,city scrape,Rental unit in Providencia · ★5.0 · 3 bedrooms...,Furnished 3 bedroom apartment located closely ...,Located in the traditional district of Provide...,https://a0.muscache.com/pictures/miso/Hosting-...,163715458,...,5.00,5.00,5.00,NaN,f,1,1,0,0,0.66
10553,6.652400e+17,https://www.airbnb.com/rooms/665239765655296713,2.023060e+13,6/28/2023,city scrape,Serviced apartment in Recoleta · ★4.80 · 2 bed...,Relájate con toda la familia en este tranquilo...,Barrio Residencial,https://a0.muscache.com/pictures/miso/Hosting-...,458667798,...,4.80,5.00,5.00,NaN,t,2,2,0,0,0.43
10556,7.853020e+17,https://www.airbnb.com/rooms/785301896834359331,2.023060e+13,6/28/2023,city scrape,Condo in Recoleta · ★4.20 · 2 bedrooms · 2 bed...,"Hermoso depto. en Recoleta: 2 dormitorios, 1 e...","El vecindario es muy tranquilo y seguro, si bi...",https://a0.muscache.com/pictures/miso/Hosting-...,486157444,...,4.00,3.90,4.20,NaN,t,1,1,0,0,1.71