# <img style="float: left; padding-right: 20px; width: 200px" src="https://raw.githubusercontent.com/raxlab/imt2200-data/main/media/logo.jpg">  IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Semestre 2025-S2**<br>
**Profesor:** Rodrigo A. Carrasco <br>

# <h1><center>Actividad 05: Limpieza y Transformación de Datos</center></h1>

Esta actividad busca aplicar los conocimientos en transformación de datos para contestar algunas preguntas.

## Instrucciones

Esto Notebook contiene las instrucciones a realizar para la actividad. 

<b>Al finalizarla, deben subir el Notebook y los archivos generados en un único archivo .zip, al módulo de la Actividad 05 en Canvas.</b>

Para esta actividad trabajarán con el archivo `spotify_history.csv`, que contiene el historial de actividad de un usuario de Spotify durante varios años.

## Rúbrica

- Si han logrado todo (con errores menores): 7.0
- Si han logrado los puntos 1 y 2 (con errores menores): 5.0
- Si no han logrado hasta el punto 2.0: 1.0

## 1. Lectura y selección de columnas

a. Primero, lea el `spotify_history.csv` con Pandas como un único DataFrame y muestre todas las columnas del archivo original.

b. Para esta actividad, las columnas de nuestro interés son las siguientes:
```
['ts','ms_played',
'master_metadata_track_name', 'master_metadata_album_artist_name',
'master_metadata_album_album_name', 'episode_name',
'episode_show_name',
'reason_start', 'reason_end']
```
Seleccione solamente estas columnas para su DataFrame de trabajo.

c. Responda:
* ¿Cuántas filas tiene su dataset?

In [2]:
# a.
import pandas as pd

df_raw = pd.read_csv('data2025/spotify_history.csv')
df_raw.columns

Index(['ts', 'platform', 'ms_played', 'conn_country',
       'master_metadata_track_name', 'master_metadata_album_artist_name',
       'master_metadata_album_album_name', 'spotify_track_uri', 'episode_name',
       'episode_show_name', 'spotify_episode_uri', 'audiobook_title',
       'audiobook_uri', 'audiobook_chapter_uri', 'audiobook_chapter_title',
       'reason_start', 'reason_end', 'shuffle', 'offline', 'offline_timestamp',
       'incognito_mode'],
      dtype='object')

In [3]:
# b.
columnas_interes = ['ts','ms_played',
'master_metadata_track_name', 'master_metadata_album_artist_name',
'master_metadata_album_album_name', 'episode_name',
'episode_show_name',
'reason_start', 'reason_end']

df_clean = df_raw.copy()

for colum in df_raw.columns:
    if colum not in columnas_interes:
        df_clean = df_clean.drop(colum, axis=1)

print(len(df_raw.columns), len(df_clean.columns))

df_clean

21 9

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,episode_name,episode_show_name,reason_start,reason_end
0,2022-12-29T16:39:18Z,753,Warning Sign,Coldplay,A Rush of Blood to the Head,NaN,NaN,fwdbtn,fwdbtn
1,2022-12-29T16:39:19Z,1661,Houdini,Foster The People,Torches,NaN,NaN,fwdbtn,fwdbtn
2,2022-12-29T16:39:21Z,1000,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,fwdbtn,fwdbtn
3,2022-12-29T16:39:22Z,1097,Waves of Nature,WILLOW,ARDIPITHECUS,NaN,NaN,fwdbtn,backbtn
4,2022-12-29T16:43:38Z,256920,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,backbtn,trackdone
...,...,...,...,...,...,...,...,...,...
41822,2025-07-13T15:18:31Z,29642,Flintstones,Jacob Collier,In My Room,NaN,NaN,clickrow,endplay
41823,2025-07-13T15:21:40Z,187573,Moon River,Jacob Collier,Djesse Vol. 2,NaN,NaN,playbtn,endplay
41824,2025-07-13T15:26:51Z,54677,Moon River,Louis Armstrong,"Hello, Dolly!",NaN,NaN,playbtn,endplay
41825,2025-07-13T15:28:54Z,122345,Moon River,Audrey Hepburn,Fruhstuck Bei Tiffany (Original Soundtrack),NaN,NaN,playbtn,endplay
41826,2025-07-15T13:45:38Z,0,Moon River - Alternate Take,Henry Mancini,Mr Lucky,NaN,NaN,trackdone,remote

In [4]:
# c.
print(f"Número de filas del dataframe: {len(df_clean)}")

Número de filas del dataframe: 41827

## 2. Limpieza


a. Revise si existen filas duplicadas en su dataset. Si es así, deje solamente la última aparición de la fila duplicada en su DataFrame. ¿Cuántas filas duplicadas hay?

b. Ahora, revise si hay filas cuyo valor en `ms_played` (milisegundos reproducidos) es menor a 1. Descarte todas estas filas.

c. ¿Cuántas filas quedaron en su DataFrame después de la limpieza?

In [5]:
# a.
print(f"Inicialmente existen {df_clean.duplicated().sum()} filas duplicadas.")
print(f"Filas únicas: {len(df_clean) - df_clean.duplicated().sum()}")

Inicialmente existen 72 filas duplicadas.
Filas únicas: 41755

In [6]:
#a.

print("\nFilas duplicadas:")
# Mostrar las primeras filas duplicadas
duplicadas = df_clean[df_clean.duplicated(keep=False)].sort_values(by=df_clean.columns.tolist())
#print(f"Total de filas involucradas en duplicados: {len(duplicadas)}")
print("Primeras 5 filas duplicadas:")
print(duplicadas.head(5))

Filas duplicadas:
Primeras 5 filas duplicadas:
                       ts  ms_played master_metadata_track_name  \
14   2022-12-30T13:07:18Z       2957               No One Knows
15   2022-12-30T13:07:18Z       2957               No One Knows
690  2023-01-10T13:05:27Z      59773                Think Twice
691  2023-01-10T13:05:27Z      59773                Think Twice
882  2023-01-16T18:12:20Z     201786                      Clean

    master_metadata_album_artist_name master_metadata_album_album_name  \
14            Queens of the Stone Age               Songs For The Deaf
15            Queens of the Stone Age               Songs For The Deaf
690                             Mo’Ju                    Native Tongue
691                             Mo’Ju                    Native Tongue
882                          Big Data                              2.0

    episode_name episode_show_name reason_start reason_end
14           NaN               NaN      appload    endplay
15           NaN               NaN      appload    endplay
690          NaN               NaN     clickrow    endplay
691          NaN               NaN     clickrow    endplay
882          NaN               NaN     clickrow  trackdone

In [7]:
#Eliminamos manteniendo la ultima paricion
filas_antes = len(df_clean)
df_sin_duplicados = df_clean.drop_duplicates(keep='last')

In [8]:
df_clean = df_sin_duplicados
print(f"\nDataFrame actualizado con {len(df_clean)} filas únicas")
df_clean

DataFrame actualizado con 41755 filas únicas

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,episode_name,episode_show_name,reason_start,reason_end
0,2022-12-29T16:39:18Z,753,Warning Sign,Coldplay,A Rush of Blood to the Head,NaN,NaN,fwdbtn,fwdbtn
1,2022-12-29T16:39:19Z,1661,Houdini,Foster The People,Torches,NaN,NaN,fwdbtn,fwdbtn
2,2022-12-29T16:39:21Z,1000,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,fwdbtn,fwdbtn
3,2022-12-29T16:39:22Z,1097,Waves of Nature,WILLOW,ARDIPITHECUS,NaN,NaN,fwdbtn,backbtn
4,2022-12-29T16:43:38Z,256920,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,backbtn,trackdone
...,...,...,...,...,...,...,...,...,...
41822,2025-07-13T15:18:31Z,29642,Flintstones,Jacob Collier,In My Room,NaN,NaN,clickrow,endplay
41823,2025-07-13T15:21:40Z,187573,Moon River,Jacob Collier,Djesse Vol. 2,NaN,NaN,playbtn,endplay
41824,2025-07-13T15:26:51Z,54677,Moon River,Louis Armstrong,"Hello, Dolly!",NaN,NaN,playbtn,endplay
41825,2025-07-13T15:28:54Z,122345,Moon River,Audrey Hepburn,Fruhstuck Bei Tiffany (Original Soundtrack),NaN,NaN,playbtn,endplay
41826,2025-07-15T13:45:38Z,0,Moon River - Alternate Take,Henry Mancini,Mr Lucky,NaN,NaN,trackdone,remote

In [9]:
# b.
df_clean['ms_played'].info() #Arroja que son 41755 entradas y 41755 son no nulas, todas del tipo int64
print((df_clean['ms_played'] < 1).sum())

<class 'pandas.core.series.Series'>
Index: 41755 entries, 0 to 41826
Series name: ms_played
Non-Null Count  Dtype
--------------  -----
41755 non-null  int64
dtypes: int64(1)
memory usage: 652.4 KB
268

In [10]:
print(f"Existen {(df_clean['ms_played'] < 1).sum()} ms_played menores a 1")

Existen 268 ms_played menores a 1

In [11]:
df_clean = df_clean[df_clean['ms_played'] > 1]
print(f"Valores de ms_played menores a 1: {(df_clean['ms_played'] < 1).sum()}")

Valores de ms_played menores a 1: 0

In [12]:
# c.
print(f"- Valores de ms_playes mayor a 1: {(df_clean['ms_played'] > 1).sum()}")
print(f"- Longitud del dataframe_clean: {len(df_clean)}")
df_clean.head()

- Valores de ms_playes mayor a 1: 41487
- Longitud del dataframe_clean: 41487

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,episode_name,episode_show_name,reason_start,reason_end
0,2022-12-29T16:39:18Z,753,Warning Sign,Coldplay,A Rush of Blood to the Head,NaN,NaN,fwdbtn,fwdbtn
1,2022-12-29T16:39:19Z,1661,Houdini,Foster The People,Torches,NaN,NaN,fwdbtn,fwdbtn
2,2022-12-29T16:39:21Z,1000,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,fwdbtn,fwdbtn
3,2022-12-29T16:39:22Z,1097,Waves of Nature,WILLOW,ARDIPITHECUS,NaN,NaN,fwdbtn,backbtn
4,2022-12-29T16:43:38Z,256920,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,backbtn,trackdone

## 3. Transformación

Aplique las siguientes transformaciones a su DataFrame:

a. La columna `ts` (timestamp) muestra la fecha y hora de reproducción de la canción. Extraiga únicamente el año y agregue una nueva columna con este dato como número entero. ¿En qué año hubo más reproducciones?

b. El dataset contiene canciones y episodios de podcasts. Genere una nueva columna (categórica o booleana) que identifique a cada fila como "canción" o "episodio" y explique cómo realizó esta clasificación. ¿Cuántas filas hay de cada una de estas categorías? 

c. Responda:
¿Cuál es el podcast con mayor número de reproducciones en total?

In [13]:
# a.
df_clean['ts'].info() #Verificamos las entradas v/s los objetos no-nulos

<class 'pandas.core.series.Series'>
Index: 41487 entries, 0 to 41825
Series name: ts
Non-Null Count  Dtype
--------------  -----
41487 non-null  object
dtypes: object(1)
memory usage: 648.2+ KB

In [23]:
df_clean['ts'] = pd.to_datetime(df_clean['ts'])
df_clean['year'] = df_clean['ts'].dt.year
df_clean.head()

/var/folders/hf/z4nqpl692qq20c0yrl9q93r40000gn/T/ipykernel_1540/592352726.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['ts'] = pd.to_datetime(df_clean['ts'])
/var/folders/hf/z4nqpl692qq20c0yrl9q93r40000gn/T/ipykernel_1540/592352726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['year'] = df_clean['ts'].dt.year

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,episode_name,episode_show_name,reason_start,reason_end,year
0,2022-12-29 16:39:18+00:00,753,Warning Sign,Coldplay,A Rush of Blood to the Head,NaN,NaN,fwdbtn,fwdbtn,2022
1,2022-12-29 16:39:19+00:00,1661,Houdini,Foster The People,Torches,NaN,NaN,fwdbtn,fwdbtn,2022
2,2022-12-29 16:39:21+00:00,1000,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,fwdbtn,fwdbtn,2022
3,2022-12-29 16:39:22+00:00,1097,Waves of Nature,WILLOW,ARDIPITHECUS,NaN,NaN,fwdbtn,backbtn,2022
4,2022-12-29 16:43:38+00:00,256920,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,backbtn,trackdone,2022

In [15]:
mas_reproducciones = df_clean.groupby("year")['ms_played'].sum() #Año con más tiempo total de reproducción
print(mas_reproducciones)

mas_reproducciones2 = df_clean["year"].value_counts() #año con más reproducciones sin considerar el tiempo
print(mas_reproducciones.idxmax(), mas_reproducciones2.idxmax())

year
2022      14595647
2023    2775477488
2024    3632080054
2025    1508225064
Name: ms_played, dtype: int64
2024 2024

El año con más reproducciones fue 2024.

In [16]:
# b.
print(df_clean.columns)
df_clean.head(10)

Index(['ts', 'ms_played', 'master_metadata_track_name',
       'master_metadata_album_artist_name', 'master_metadata_album_album_name',
       'episode_name', 'episode_show_name', 'reason_start', 'reason_end',
       'year'],
      dtype='object')

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,episode_name,episode_show_name,reason_start,reason_end,year
0,2022-12-29 16:39:18+00:00,753,Warning Sign,Coldplay,A Rush of Blood to the Head,NaN,NaN,fwdbtn,fwdbtn,2022
1,2022-12-29 16:39:19+00:00,1661,Houdini,Foster The People,Torches,NaN,NaN,fwdbtn,fwdbtn,2022
2,2022-12-29 16:39:21+00:00,1000,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,fwdbtn,fwdbtn,2022
3,2022-12-29 16:39:22+00:00,1097,Waves of Nature,WILLOW,ARDIPITHECUS,NaN,NaN,fwdbtn,backbtn,2022
4,2022-12-29 16:43:38+00:00,256920,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,backbtn,trackdone,2022
5,2022-12-29 16:47:31+00:00,231813,Waves of Nature,WILLOW,ARDIPITHECUS,NaN,NaN,trackdone,trackdone,2022
6,2022-12-29 16:52:18+00:00,286760,Feet off the Ground,Cut Capers,Metropolis,NaN,NaN,trackdone,trackdone,2022
7,2022-12-29 17:15:29+00:00,153849,Get Movin' (Feet Don't Fail Me Now),Cut Capers,Metropolis,NaN,NaN,trackdone,logout,2022
8,2022-12-29 21:41:25+00:00,193733,Paralyzed,The Used,Lies for the Liars,NaN,NaN,playbtn,trackdone,2022
9,2022-12-29 21:44:51+00:00,197866,Blood on My Hands,The Used,Artwork,NaN,NaN,trackdone,trackdone,2022

In [ ]:
categorias = df_clean['master_metadata_track_name'].unique()
print(df_clean['episode_name'].describe())
print("="*20)
print(df_clean['episode_name'].info())

count                                                   924
unique                                                  547
top       39: The Pill, The 2 Highest Points on Earth, a...
freq                                                      7
Name: episode_name, dtype: object
====================
<class 'pandas.core.series.Series'>
Index: 41487 entries, 0 to 41825
Series name: episode_name
Non-Null Count  Dtype
--------------  -----
924 non-null    object
dtypes: object(1)
memory usage: 648.2+ KB
None

In [ ]:
#El dataset contiene canciones y episodios de podcasts. 
# Genere una nueva columna (categórica o booleana) que identifique a cada fila como "canción" o "episodio" y explique cómo realizó esta clasificación. 
# ¿Cuántas filas hay de cada una de estas categorías?

podcast = df_clean[df_clean['episode_name'].notna()]
podcast.head()

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,episode_name,episode_show_name,reason_start,reason_end,year
50,2022-12-31 12:19:35+00:00,641,NaN,NaN,NaN,Episode 42: Time to Kill,Wolf 359,clickrow,endplay,2022
51,2022-12-31 12:19:41+00:00,882,NaN,NaN,NaN,Episode 43: Persuasion,Wolf 359,trackdone,endplay,2022
52,2022-12-31 12:54:51+00:00,2010138,NaN,NaN,NaN,Episode 42: Time to Kill,Wolf 359,clickrow,unexpected-exit-while-paused,2022
1070,2023-01-29 06:53:42+00:00,6705086,NaN,NaN,NaN,"32: The Ozone Success Story, Turning Heads, an...",Let's Learn Everything!,clickrow,endplay,2023
1071,2023-01-29 06:53:45+00:00,1021,NaN,NaN,NaN,30: The HaLearnDay Spectacular!,Let's Learn Everything!,clickrow,unexpected-exit,2023

In [26]:
df_clean['tipo'] = (
    df_clean['episode_name']
    .notna()
    .map({True: "episodio",False: "canción"})
    .astype('category')
    )
df_clean

/var/folders/hf/z4nqpl692qq20c0yrl9q93r40000gn/T/ipykernel_1540/3594240286.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['tipo'] = (

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,episode_name,episode_show_name,reason_start,reason_end,year,tipo
0,2022-12-29 16:39:18+00:00,753,Warning Sign,Coldplay,A Rush of Blood to the Head,NaN,NaN,fwdbtn,fwdbtn,2022,canción
1,2022-12-29 16:39:19+00:00,1661,Houdini,Foster The People,Torches,NaN,NaN,fwdbtn,fwdbtn,2022,canción
2,2022-12-29 16:39:21+00:00,1000,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,fwdbtn,fwdbtn,2022,canción
3,2022-12-29 16:39:22+00:00,1097,Waves of Nature,WILLOW,ARDIPITHECUS,NaN,NaN,fwdbtn,backbtn,2022,canción
4,2022-12-29 16:43:38+00:00,256920,Fingerprints,Hiatus Kaiyote,Choose Your Weapon,NaN,NaN,backbtn,trackdone,2022,canción
...,...,...,...,...,...,...,...,...,...,...,...
41821,2025-07-13 15:17:37+00:00,116308,Salmo de la Rosa Verdadera,Inti-Illimani,Lugares Comunes,NaN,NaN,trackdone,endplay,2025,canción
41822,2025-07-13 15:18:31+00:00,29642,Flintstones,Jacob Collier,In My Room,NaN,NaN,clickrow,endplay,2025,canción
41823,2025-07-13 15:21:40+00:00,187573,Moon River,Jacob Collier,Djesse Vol. 2,NaN,NaN,playbtn,endplay,2025,canción
41824,2025-07-13 15:26:51+00:00,54677,Moon River,Louis Armstrong,"Hello, Dolly!",NaN,NaN,playbtn,endplay,2025,canción
41825,2025-07-13 15:28:54+00:00,122345,Moon River,Audrey Hepburn,Fruhstuck Bei Tiffany (Original Soundtrack),NaN,NaN,playbtn,endplay,2025,canción

In [18]:
# c.

El podcast con más reproducciones es XXX, con YYY reproducciones.

## 4. Variables categóricas

a. Las columnas `reason_start`y `reason_end` muestran, respectivamente, por qué se comenzó y se terminó la reproducción de una pista. Estas son columnas categóricas. Para ambas, muestre todas las categorías que aparecen en su dataset.
¿Son las mismas? Comente.

b. Vamos a crear una nueva columna llamada `skipped` (categórica o booleana), que identificará si la reproducción de la pista fue interrumpida intencionalmente por el usuario (saltada). Para esto, nos fijaremos en el valor de `reason_end` de cada fila. Considere una pista como "skipped" si su término está entre las siguientes categorías: `endplay`, `fwdbtn`, `backbtn`, y como "not skipped" en caso contrario.

c. Finalmente, responda:
¿Cuál es la canción más interrumpida (o saltada)? Responda con el nombre de la canción y el artista.

In [19]:
# a.

In [20]:
# b.

In [21]:
# c.

La canción más interrumpida por el usuario es XXX.